// songs.js - Your Master Playlist Database
const defaultSongs = [
    // --- Hindi Songs ---
    {title: "Kesariya", artist: "Brahmāstra", cover: "https://picsum.photos/200?random=1", file: "https://files.catbox.moe/mn42vj.mp3", language: "Hindi"},
    {title: "Bulleya", artist: "Sultan", cover: "https://picsum.photos/200?random=3", file: "https://files.catbox.moe/195dty.mp3", language: "Hindi"},
    {title: "Tabaahi", artist: "Toxic", cover: "https://picsum.photos/200?random=4", file: "https://files.catbox.moe/m37ohm.mp3", language: "Hindi"},
    {title: "Rai Rai Raa Raa", artist: "Toxic", cover: "https://picsum.photos/200?random=5", file: "https://files.catbox.moe/no3t0i.mp3", language: "Hindi"},
    {title: "Aari Aari", artist: "Dhurandhar-2", cover: "https://picsum.photos/200?random=7", file: "https://files.catbox.moe/4a3svo.mp3", language: "Hindi"},
    {title: "Monica", artist: "Unknown", cover: "https://picsum.photos/200?random=12", file: "https://files.catbox.moe/xcon2x.mp3", language: "Hindi"},
    {title: "Saari Dunia Jala Denge", artist: "Unknown", cover: "https://picsum.photos/200?random=13", file: "https://files.catbox.moe/gdvpfj.mp3", language: "Hindi"},
    {title: "Jehda Nasha", artist: "Unknown", cover: "https://picsum.photos/200?random=14", file: "https://files.catbox.moe/k1353t.mp3", language: "Hindi"},
    {title: "Humsafar", artist: "Unknown", cover: "https://picsum.photos/200?random=15", file: "https://files.catbox.moe/zz0p4x.mp3", language: "Hindi"},
    {title: "Milegi Milegi", artist: "Unknown", cover: "https://picsum.photos/200?random=16", file: "https://files.catbox.moe/vzerhk.mp3", language: "Hindi"},
    {title: "Dil Toh Pagal Hai (Remix)", artist: "Unknown", cover: "https://picsum.photos/200?random=17", file: "https://files.catbox.moe/61opop.mp3", language: "Hindi"},
    {title: "Gulabi Sharara", artist: "Unknown", cover: "https://picsum.photos/200?random=18", file: "https://files.catbox.moe/i8eh73.mp3", language: "Hindi"},
    {title: "Jhoom Barabar Jhoom", artist: "Unknown", cover: "https://picsum.photos/200?random=19", file: "https://files.catbox.moe/b7dufq.mp3", language: "Hindi"},
    {title: "Tera Ban Jaunga", artist: "Unknown", cover: "https://picsum.photos/200?random=20", file: "https://files.catbox.moe/refnex.mp3", language: "Hindi"},
    {title: "Tere Ishq Mein", artist: "Unknown", cover: "https://picsum.photos/200?random=21", file: "https://files.catbox.moe/sr7g2i.mp3", language: "Hindi"},
    {title: "Jhoom Sharabi", artist: "Unknown", cover: "https://picsum.photos/200?random=22", file: "https://files.catbox.moe/1ptlvm.mp3", language: "Hindi"},
    {title: "Phurr", artist: "Unknown", cover: "https://picsum.photos/200?random=23", file: "https://files.catbox.moe/4fv4ue.mp3", language: "Hindi"},
    {title: "Besharam Rang", artist: "Unknown", cover: "https://picsum.photos/200?random=24", file: "https://files.catbox.moe/8ndo0l.mp3", language: "Hindi"},
    {title: "Saibo", artist: "Unknown", cover: "https://picsum.photos/200?random=25", file: "https://files.catbox.moe/dhshrk.mp3", language: "Hindi"},
    {title: "Raanjhana", artist: "Unknown", cover: "https://picsum.photos/200?random=28", file: "https://files.catbox.moe/cellz4.mp3", language: "Hindi"},
    {title: "Haseen", artist: "Unknown", cover: "https://picsum.photos/200?random=29", file: "https://files.catbox.moe/eorv0j.mp3", language: "Hindi"},
    {title: "Ishq Jalakar", artist: "Unknown", cover: "https://picsum.photos/200?random=30", file: "https://files.catbox.moe/9xumb2.mp3", language: "Hindi"},
    {title: "Gehra Hua", artist: "Unknown", cover: "https://picsum.photos/200?random=31", file: "https://files.catbox.moe/kzlz70.mp3", language: "Hindi"},
    {title: "Laagi Re Lagan", artist: "Unknown", cover: "https://picsum.photos/200?random=32", file: "https://files.catbox.moe/n9qgtq.mp3", language: "Hindi"},

    // --- Telugu / South Songs ---
    {title: "Thalapathy Kacheri", artist: "Unknown", cover: "https://picsum.photos/200?random=26", file: "https://files.catbox.moe/l6shmk.mp3", language: "Telugu"},
    {title: "Chikiri Chikiri", artist: "Unknown", cover: "https://picsum.photos/200?random=33", file: "https://files.catbox.moe/y0df1k.mp3", language: "Telugu"},
    {title: "Chiru Chiru", artist: "Unknown", cover: "https://picsum.photos/200?random=34", file: "https://files.catbox.moe/9geklv.mp3", language: "Telugu"},
    {title: "Nee Yadalo", artist: "Unknown", cover: "https://picsum.photos/200?random=35", file: "https://files.catbox.moe/6dtk2w.mp3", language: "Telugu"},
    {title: "Ninnu Chuse Anandamlo", artist: "Unknown", cover: "https://picsum.photos/200?random=36", file: "https://files.catbox.moe/t05z8d.mp3", language: "Telugu"},
    {title: "Hoyna Hoyna", artist: "Unknown", cover: "https://picsum.photos/200?random=37", file: "https://files.catbox.moe/odv2p2.mp3", language: "Telugu"},
    {title: "Hello Rammante", artist: "Unknown", cover: "https://picsum.photos/200?random=38", file: "https://files.catbox.moe/6ic1li.mp3", language: "Telugu"},
    {title: "Ola Olaala Ala", artist: "Unknown", cover: "https://picsum.photos/200?random=39", file: "https://files.catbox.moe/w7b93p.mp3", language: "Telugu"},
    {title: "Chilipiga", artist: "Unknown", cover: "https://picsum.photos/200?random=40", file: "https://files.catbox.moe/f8vhp1.mp3", language: "Telugu"},
    {title: "Nenu Nuvvantu", artist: "Unknown", cover: "https://picsum.photos/200?random=41", file: "https://files.catbox.moe/gvglj1.mp3", language: "Telugu"},
    {title: "Rooba Rooba", artist: "Unknown", cover: "https://picsum.photos/200?random=42", file: "https://files.catbox.moe/n86g5c.mp3", language: "Telugu"},
    {title: "O Range", artist: "Unknown", cover: "https://picsum.photos/200?random=43", file: "https://files.catbox.moe/1v6ctl.mp3", language: "Telugu"},

    // --- Punjabi Songs ---
    {title: "Boyfriend", artist: "Karan Aujla", cover: "https://picsum.photos/200?random=2", file: "https://files.catbox.moe/fcllvp.mp3", language: "Punjabi"},
    {title: "You Are You Though", artist: "Karan Aujla", cover: "https://picsum.photos/200?random=9", file: "https://files.catbox.moe/hcselx.mp3", language: "Punjabi"},
    {title: "MF Gabhru", artist: "Unknown", cover: "https://picsum.photos/200?random=8", file: "https://files.catbox.moe/bc3mcw.mp3", language: "Punjabi"},
    {title: "Pal Pal", artist: "Talwinder", cover: "https://picsum.photos/200?random=27", file: "https://files.catbox.moe/x31ls3.mp3", language: "Punjabi"},
    {title: "I Really Do", artist: "Unknown", cover: "https://picsum.photos/200?random=10", file: "https://files.catbox.moe/hs231u.mp3", language: "Punjabi"},
    {title: "For A Reason", artist: "Unknown", cover: "https://picsum.photos/200?random=11", file: "https://files.catbox.moe/eq7c5h.mp3", language: "Punjabi"},

    // --- English Songs ---
    {title: "Shape of You", artist: "Ed Sheeran", cover: "https://picsum.photos/200?random=44", file: "https://files.catbox.moe/h6sxqt.mp3", language: "English"},
    {title: "Believer", artist: "Imagine Dragons", cover: "https://picsum.photos/200?random=45", file: "https://files.catbox.moe/zvhemy.mp3", language: "English"},
    {title: "Faded", artist: "Alan Walker", cover: "https://picsum.photos/200?random=46", file: "https://files.catbox.moe/9q4oau.mp3", language: "English"},
    {title: "Love Me Like You Do", artist: "Ellie Goulding", cover: "https://picsum.photos/200?random=47", file: "https://files.catbox.moe/xryip4.mp3", language: "English"},
    {title: "Blinding Lights", artist: "The Weeknd", cover: "https://picsum.photos/200?random=48", file: "https://files.catbox.moe/7aixbg.mp3", language: "English"},
    {title: "Sorry (Instrumental)", artist: "Justin Bieber", cover: "https://picsum.photos/200?random=49", file: "https://files.catbox.moe/a6ua2y.mp3", language: "English"},
    {title: "I Don't Care", artist: "Ed Sheeran & Justin Bieber", cover: "https://picsum.photos/200?random=50", file: "https://files.catbox.moe/6psg3z.mp3", language: "English"},
    {title: "Montero (Call Me By Your Name)", artist: "Lil Nas X", cover: "https://picsum.photos/200?random=51", file: "https://files.catbox.moe/qtycw9.mp3", language: "English"},
    {title: "Closer", artist: "The Chainsmokers", cover: "https://picsum.photos/200?random=52", file: "https://files.catbox.moe/utqgb3.mp3", language: "English"},
    {title: "Bones", artist: "Imagine Dragons", cover: "https://picsum.photos/200?random=53", file: "https://files.catbox.moe/p7r6di.mp3", language: "English"},
    {title: "Night Changes", artist: "One Direction", cover: "https://picsum.photos/200?random=54", file: "https://files.catbox.moe/86w14g.mp3", language: "English"},
    {title: "Middle of the Night", artist: "Elley Duhé", cover: "https://picsum.photos/200?random=55", file: "https://files.catbox.moe/43uyau.mp3", language: "English"}
];
