// songs.js - Your Master Playlist Database
const defaultSongs = [
    // --- Original Songs ---
    {title: "Kesariya (Hindi)", artist: "Brahmāstra", cover: "https://picsum.photos/200?random=1", file: "https://files.catbox.moe/mn42vj.mp3"},
    {title: "Boyfriend", artist: "Karan Aujla", cover: "https://picsum.photos/200?random=2", file: "https://files.catbox.moe/fcllvp.mp3"},
    {title: "Bulleya", artist: "Sultan", cover: "https://picsum.photos/200?random=3", file: "https://files.catbox.moe/195dty.mp3"},
    {title: "Tabaahi", artist: "Toxic", cover: "https://picsum.photos/200?random=4", file: "https://files.catbox.moe/m37ohm.mp3"},
    {title: "Rai Rai Raa Raa", artist: "Toxic", cover: "https://picsum.photos/200?random=5", file: "https://files.catbox.moe/no3t0i.mp3"},
    {title: "Aari Aari", artist: "Dhurandhar-2", cover: "https://picsum.photos/200?random=7", file: "https://files.catbox.moe/4a3svo.mp3"},
    {title: "MF Gabhru", artist: "Unknown", cover: "https://picsum.photos/200?random=8", file: "https://files.catbox.moe/bc3mcw.mp3"},
    {title: "You Are You Though", artist: "Karan Aujla", cover: "https://picsum.photos/200?random=9", file: "https://files.catbox.moe/hcselx.mp3"},
    {title: "I Really Do", artist: "Unknown", cover: "https://picsum.photos/200?random=10", file: "https://files.catbox.moe/hs231u.mp3"},
    {title: "For A Reason", artist: "Unknown", cover: "https://picsum.photos/200?random=11", file: "https://files.catbox.moe/eq7c5h.mp3"},

    // --- Newly Added Songs ---
    {title: "Monica", artist: "Unknown", cover: "https://picsum.photos/200?random=12", file: "https://files.catbox.moe/xcon2x.mp3"},
    {title: "Saari Dunia Jala Denge", artist: "Unknown", cover: "https://picsum.photos/200?random=13", file: "https://files.catbox.moe/gdvpfj.mp3"},
    {title: "Jehda Nasha", artist: "Unknown", cover: "https://picsum.photos/200?random=14", file: "https://files.catbox.moe/k1353t.mp3"},
    {title: "Humsafar", artist: "Unknown", cover: "https://picsum.photos/200?random=15", file: "https://files.catbox.moe/zz0p4x.mp3"},
    {title: "Milegi Milegi", artist: "Unknown", cover: "https://picsum.photos/200?random=16", file: "https://files.catbox.moe/vzerhk.mp3"},
    {title: "Dil Toh Pagal Hai (Remix)", artist: "Unknown", cover: "https://picsum.photos/200?random=17", file: "https://files.catbox.moe/61opop.mp3"},
    {title: "Gulabi Sharara", artist: "Unknown", cover: "https://picsum.photos/200?random=18", file: "https://files.catbox.moe/i8eh73.mp3"},
    {title: "Jhoom Barabar Jhoom", artist: "Unknown", cover: "https://picsum.photos/200?random=19", file: "https://files.catbox.moe/b7dufq.mp3"},
    {title: "Tera Ban Jaunga", artist: "Unknown", cover: "https://picsum.photos/200?random=20", file: "https://files.catbox.moe/refnex.mp3"},
    {title: "Tere Ishq Mein", artist: "Unknown", cover: "https://picsum.photos/200?random=21", file: "https://files.catbox.moe/sr7g2i.mp3"},
    {title: "Jhoom Sharabi", artist: "Unknown", cover: "https://picsum.photos/200?random=22", file: "https://files.catbox.moe/1ptlvm.mp3"},
    {title: "Phurr", artist: "Unknown", cover: "https://picsum.photos/200?random=23", file: "https://files.catbox.moe/4fv4ue.mp3"},
    {title: "Besharam Rang", artist: "Unknown", cover: "https://picsum.photos/200?random=24", file: "https://files.catbox.moe/8ndo0l.mp3"},
    {title: "Saibo", artist: "Unknown", cover: "https://picsum.photos/200?random=25", file: "https://files.catbox.moe/dhshrk.mp3"},
    {title: "Thalapathy Kacheri", artist: "Unknown", cover: "https://picsum.photos/200?random=26", file: "https://files.catbox.moe/l6shmk.mp3"},
    {title: "Pal Pal", artist: "Talwinder", cover: "https://picsum.photos/200?random=27", file: "https://files.catbox.moe/x31ls3.mp3"},
    {title: "Raanjhana", artist: "Unknown", cover: "https://picsum.photos/200?random=28", file: "https://files.catbox.moe/cellz4.mp3"},
    {title: "Haseen", artist: "Unknown", cover: "https://picsum.photos/200?random=29", file: "https://files.catbox.moe/eorv0j.mp3"},
    {title: "Ishq Jalakar", artist: "Unknown", cover: "https://picsum.photos/200?random=30", file: "https://files.catbox.moe/9xumb2.mp3"},
    {title: "Gehra Hua", artist: "Unknown", cover: "https://picsum.photos/200?random=31", file: "https://files.catbox.moe/kzlz70.mp3"},
    {title: "Laagi Re Lagan", artist: "Unknown", cover: "https://picsum.photos/200?random=32", file: "https://files.catbox.moe/n9qgtq.mp3"},
    {title: "Chikiri Chikiri", artist: "Unknown", cover: "https://picsum.photos/200?random=33", file: "https://files.catbox.moe/y0df1k.mp3"},
    {title: "Chiru Chiru", artist: "Unknown", cover: "https://picsum.photos/200?random=34", file: "https://files.catbox.moe/9geklv.mp3"},
    {title: "Nee Yadalo", artist: "Unknown", cover: "https://picsum.photos/200?random=35", file: "https://files.catbox.moe/6dtk2w.mp3"},
    {title: "Ninnu Chuse Anandamlo", artist: "Unknown", cover: "https://picsum.photos/200?random=36", file: "https://files.catbox.moe/t05z8d.mp3"},
    {title: "Hoyna Hoyna", artist: "Unknown", cover: "https://picsum.photos/200?random=37", file: "https://files.catbox.moe/odv2p2.mp3"},
    {title: "Hello Rammante", artist: "Unknown", cover: "https://picsum.photos/200?random=38", file: "https://files.catbox.moe/6ic1li.mp3"},
    {title: "Ola Olaala Ala", artist: "Unknown", cover: "https://picsum.photos/200?random=39", file: "https://files.catbox.moe/w7b93p.mp3"},
    {title: "Chilipiga", artist: "Unknown", cover: "https://picsum.photos/200?random=40", file: "https://files.catbox.moe/f8vhp1.mp3"},
    {title: "Nenu Nuvvantu", artist: "Unknown", cover: "https://picsum.photos/200?random=41", file: "https://files.catbox.moe/gvglj1.mp3"},
    {title: "Rooba Rooba", artist: "Unknown", cover: "https://picsum.photos/200?random=42", file: "https://files.catbox.moe/n86g5c.mp3"},
    {title: "O Range", artist: "Unknown", cover: "https://picsum.photos/200?random=43", file: "https://files.catbox.moe/1v6ctl.mp3"}
];
